version: 2
jobs:
  build:
    working_directory: ~/vzvol_build
    docker:
      - image: circleci/ubuntu-server:latest
    steps:
      - checkout
      - run:
          name: InstallDeps
          command: apt-get update && apt-get -y install pv dialog xfsprogs dosfstools ruby2.0 ruby2.0-dev gcc make
      - run:
          name: InstallGems
          command: gem2.0 install fpm --no-ri --no-doc
      - run:
          name: BuildPkgDeb
          command: sh ~/vzvol_build/build/vzvol_build.sh 0.6.4 deb ~/vzvol_build rainbow@sanitylinux.org
      - run:
          name: InstallPkg
          command: dpkg -i ~/vzvol_build/vzvol_0.6.4_all.deb
      - run:
          name: TestPkg
          command: sudo /usr/local/bin/vzvol --list
