version: 2
jobs:
  build:
    working_directory: ~/vzvol_build
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: InstallDeps
          command: sudo add-apt-repository -y ppa:zfs-native/stable && sudo apt-get update && sudo apt-get -y install pv dialog xfsprogs dosfstools ruby2.0 ruby2.0-dev gcc make zfsutils
      - run:
          name: kldload
          command: sudo modprobe zfs
      - run:
          name: InstallGems
          command: sudo gem2.0 install fpm --no-ri --no-doc
      - run:
          name: BuildPkgDeb
          command: sh ~/vzvol_build/build/vzvol_build.sh 0.6.4 deb ~/vzvol_build rainbow@sanitylinux.org
      - run:
          name: InstallPkg
          command: sudo dpkg -i ~/vzvol_build/vzvol_0.6.4_all.deb
      - run:
          name: CreateDiskImage
          command: sudo dd if=/dev/zero of=/root/zpool bs=10M count=1024
      - run:
          name: CreateZpool
          command: sudo zpool create vzvoltestpool /root/zpool
      - run:
          name: TestPkg
          command: sudo /usr/local/bin/vzvol --list
