version: 2
jobs:
  build:
    working_directory: ~/vzvol_build
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: InstallDeps
          command: sudo add-apt-repository -y ppa:zfs-native/stable && ( if [ ! -d /etc/apt/sources.d ]; then sudo mkdir /etc/apt/sources.d; fi && sudo touch /etc/apt/sources.d/virtualbox.list && echo "deb https://download.virtualbox.org/virtualbox/debian trusty contrib" | sudo tee -a /etc/apt/sources.d/virtualbox.list ) && ( wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add - ) && sudo apt-get update && sudo apt-get -y install pv dialog xfsprogs dosfstools ruby2.0 ruby2.0-dev gcc make linux-headers-4.4.0-96-generic 
      - run:
          name: InstallVBox
          command: sudo apt-get install -y virtualbox
      - run:
          name: InstallZFS
          command: sudo apt-get install -y ubuntu-zfs zfs-dkms
      - run:
          name: kldload
          command: sudo modprobe zfs
      - run:
          name: InstallGems
          command: sudo gem2.0 install fpm --no-ri --no-doc
      - run:
          name: BuildPkgDeb
          command: sudo sh ~/vzvol_build/build/vzvol_build.sh 0.6.4 deb ~/vzvol_build rainbow@sanitylinux.org
      - run:
          name: InstallPkg
          command: sudo dpkg -i ~/vzvol_build/vzvol_0.6.4_all.deb
      - run:
          name: CreateDiskImage
          command: sudo dd if=/dev/zero of=/root/vzvolpool.img bs=1024M count=10
      - run:
          name: CreateZpool
          command: sudo zpool create vzvoltestpool /root/vzvolpool.img
      - run:
          name: TestCreate
          command: sudo /usr/local/bin/vzvol -t virtualbox -v HorseTest -s 512M
      - run:
          name: TestCreateRaw
          command: sudo /usr/local/bin/vzvol -t raw -v HorseTest2 -s 20M
      - run:
          name: TestList
          command: sudo /usr/local/bin/vzvol --list
      - run:
          name: TestDelete
          command: sudo /usr/local/bin/vzvol --delete -f vzvoltestpool/HorseTest
      - run:
          name: TestDeleteRaw
          command: sudo /usr/local/bin/vzvol --delete -f vzvoltestpool/HorseTest2
      - run:
          name: MakeSureDeleteWorked
          command: ( sudo /usr/local/bin/vzvol --list ); if [ $? = 1 ]; then return 0; fi && ls -lah ~/Vboxdisks/ 